export { DIMENSIONS } from './dimensions'
export type { DimensionId, DimensionScores } from './dimensions'
export { QUESTIONS } from './questions'
export type { Question, QuestionType, Choice } from './questions'
export { processQuizResults, calculateMatchScores } from './scoring'
export type { QuizResponse, AllResponses } from './scoring'
export { DIMENSION_TEXTS, generateActe4 } from './result-texts'
