-- Add subtitle, category, and is_original fields to douleurs table
-- so that all encyclopédie topics can be managed from the backoffice

ALTER TABLE douleurs ADD COLUMN IF NOT EXISTS subtitle text;
ALTER TABLE douleurs ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE douleurs ADD COLUMN IF NOT EXISTS is_original boolean DEFAULT false;

-- Update existing douleurs that match known original topics
-- (they'll get their subtitle/category set via the admin panel or seed below)

-- Seed all 170+ encyclopédie topics as douleurs entries
-- Uses ON CONFLICT to avoid duplicating existing entries (matched by slug)
-- Existing douleurs keep their content; new ones are created as placeholders

-- First ensure slug has a unique constraint for upsert
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'douleurs_slug_unique'
  ) THEN
    ALTER TABLE douleurs ADD CONSTRAINT douleurs_slug_unique UNIQUE (slug);
  END IF;
END $$;

INSERT INTO douleurs (title, slug, subtitle, category, is_original, is_active, is_published)
VALUES
  ('Abandon', 'abandon', 'grandir sans père, sans mère ou sans les deux', 'Blessures & Traumatismes', true, true, false),
  ('Abus émotionnels', 'abus-emotionnels', 'identifier, comprendre et guérir', 'Blessures & Traumatismes', false, true, false),
  ('Abus sexuels', 'abus-sexuels', 'identifier, comprendre et guérir', 'Blessures & Traumatismes', true, true, false),
  ('Addiction', 'addiction', 'alcool, drogues, jeux, écrans, travail, sucre', 'Émotions & Psychologie', false, true, false),
  ('Adolescence', 'adolescence', 'traverser cette période et en comprendre les blessures', 'Vie & Expériences', false, true, false),
  ('Affirmation de soi', 'affirmation-de-soi', 'assertivité, s''exprimer sans s''effacer', 'Développement Personnel', false, true, false),
  ('Âge & vieillissement', 'age-vieillissement', 'accepter le passage du temps et se réinventer', 'Vie & Expériences', false, true, false),
  ('Âme', 'ame', 'connexion à l''âme, mission de l''âme', 'Spiritualité & Énergie', false, true, false),
  ('Amour conditionnel', 'amour-conditionnel', 'l''amour conditionnel vs inconditionnel — comprendre la différence', 'Relations & Liens', false, true, false),
  ('Amour de soi', 'amour-de-soi', 'développer l''amour et l''estime de soi', 'Développement Personnel', true, true, false),
  ('Ancêtres & mémoires ancestrales', 'ancetres-memoires-ancestrales', 'héritage familial, messages des lignées', 'Spiritualité & Énergie', false, true, false),
  ('Ancrage (Grounding)', 'ancrage-grounding', 'se sentir ancré dans son corps, dans le présent', 'Corps & Somatique', false, true, false),
  ('Angoisse existentielle', 'angoisse-existentielle', 'le vide, la mort, le sens — apprivoiser l''angoisse profonde', 'Émotions & Psychologie', false, true, false),
  ('Anxiété', 'anxiete', 'comprendre et apprendre à la gérer', 'Émotions & Psychologie', true, true, false),
  ('Archives akashiques', 'archives-akashiques', 'accéder à la mémoire de l''âme', 'Spiritualité & Énergie', false, true, false),
  ('Assertivité', 'assertivite', 's''affirmer sans agresser ni s''effacer', 'Développement Personnel', false, true, false),
  ('Astrologie', 'astrologie', 'se connaître via les astres, thème natal et évolution', 'Pratiques & Outils', false, true, false),
  ('Attachement', 'attachement', 'styles d''attachement : sécure, anxieux, évitant, désorganisé', 'Relations & Liens', false, true, false),
  ('Attentes', 'attentes', 'se libérer des attentes des autres et de soi-même', 'Développement Personnel', false, true, false),
  ('Aura', 'aura', 'comprendre et travailler son champ énergétique', 'Spiritualité & Énergie', false, true, false),
  ('Authenticité', 'authenticite', 'vivre en accord avec ce qu''on est vraiment', 'Identité & Mission', false, true, false),
  ('Autorité intérieure', 'autorite-interieure', 'faire confiance à sa propre voix intérieure', 'Développement Personnel', false, true, false),
  ('Autocompassion', 'autocompassion', 'se traiter avec douceur et bienveillance', 'Développement Personnel', false, true, false),
  ('Autosabotage', 'autosabotage', 'reconnaître et défaire les patterns autodestructeurs', 'Émotions & Psychologie', false, true, false),
  ('Ayurveda', 'ayurveda', 'médecine ancienne, connaissance des doshas, équilibre naturel', 'Soins & Thérapies', false, true, false),
  ('Blessures de l''âme', 'blessures-de-lame', 'les 5 blessures fondamentales selon Lise Bourbeau', 'Blessures & Traumatismes', false, true, false),
  ('Blessures relationnelles', 'blessures-relationnelles', 'les traces que les autres laissent sur notre capacité à aimer', 'Blessures & Traumatismes', false, true, false),
  ('Bonheur', 'bonheur', 'construire un bonheur durable, pas dépendant des circonstances', 'Développement Personnel', false, true, false),
  ('Breathwork', 'breathwork', 'respiration consciente et holotropique comme outil de guérison', 'Soins & Thérapies', false, true, false),
  ('Burnout', 'burnout', 'comprendre, prévenir et traverser l''épuisement total', 'Émotions & Psychologie', false, true, false),
  ('But de vie', 'but-de-vie', 'trouver sa raison d''être profonde', 'Identité & Mission', false, true, false),
  ('Chakras', 'chakras', 'les 7 centres énergétiques, leurs déséquilibres et leur activation', 'Spiritualité & Énergie', false, true, false),
  ('Champ morphogénétique', 'champ-morphogenetique', 'l''invisible qui relie et structure tous les êtres vivants', 'Spiritualité & Énergie', false, true, false),
  ('Codépendance', 'codependance', 'perdre soi pour sauver l''autre — comprendre et sortir du cycle', 'Relations & Liens', false, true, false),
  ('Cohérence cardiaque', 'coherence-cardiaque', 'réguler le système nerveux par la respiration cardiaque', 'Soins & Thérapies', false, true, false),
  ('Colère', 'colere', 'libérer la colère et le ressentiment', 'Émotions & Psychologie', true, true, false),
  ('Communication non-violente', 'communication-non-violente', 'CNV — s''exprimer sans blesser, écouter sans se perdre', 'Relations & Liens', false, true, false),
  ('Comparaison sociale', 'comparaison-sociale', 'sortir du piège des comparaisons permanentes', 'Émotions & Psychologie', false, true, false),
  ('Conditionnement', 'conditionnement', 'identifier et dépasser les conditionnements de l''enfance', 'Blessures & Traumatismes', true, true, false),
  ('Confiance en soi', 'confiance-en-soi', 'surmonter les peurs et apprendre à oser', 'Développement Personnel', true, true, false),
  ('Congruence', 'congruence', 'alignement intérieur — penser, ressentir, agir en accord', 'Identité & Mission', false, true, false),
  ('Conscience', 'conscience', 'élargir sa conscience de soi et du monde', 'Spiritualité & Énergie', false, true, false),
  ('Constellations familiales', 'constellations-familiales', 'méthode Hellinger — révéler les loyautés et dynamiques cachées', 'Soins & Thérapies', false, true, false),
  ('Contrôle', 'controle', 'besoin de contrôle, hypercontrôle et chemin vers le lâcher-prise', 'Émotions & Psychologie', false, true, false),
  ('Corps & esprit', 'corps-esprit', 'la connexion fondamentale entre le physique et l''émotionnel', 'Corps & Somatique', false, true, false),
  ('Couple', 'couple', 'dynamiques, besoins, conflits et épanouissement à deux', 'Relations & Liens', false, true, false),
  ('Créativité', 'creativite', 'libérer la créativité bloquée par la peur du jugement', 'Développement Personnel', false, true, false),
  ('Cristaux & lithothérapie', 'cristaux-lithotherapie', 'propriétés vibratoires des pierres et usage thérapeutique', 'Soins & Thérapies', false, true, false),
  ('Croyances limitantes', 'croyances-limitantes', 'identifier et reprogrammer les croyances qui bloquent', 'Émotions & Psychologie', false, true, false),
  ('Culpabilité', 'culpabilite', 'comprendre la culpabilité saine et toxique', 'Émotions & Psychologie', false, true, false),
  ('Cycles de vie', 'cycles-de-vie', 'les grandes transitions qui transforment une vie', 'Vie & Expériences', false, true, false),
  ('Cycles lunaires', 'cycles-lunaires', 'se synchroniser avec les phases de la lune', 'Pratiques & Outils', false, true, false),
  ('Danse-thérapie', 'danse-therapie', 'le mouvement du corps comme langage de guérison', 'Soins & Thérapies', false, true, false),
  ('Décodage biologique', 'decodage-biologique', 'comprendre le message des maladies et symptômes', 'Corps & Somatique', false, true, false),
  ('Déni', 'deni', 'mécanisme de défense — voir ce qu''on refuse de voir', 'Émotions & Psychologie', false, true, false),
  ('Dépendance affective', 'dependance-affective', 'comprendre et s''en libérer', 'Relations & Liens', true, true, false),
  ('Dépression', 'depression', 'comprendre et surmonter', 'Émotions & Psychologie', true, true, false),
  ('Désirs profonds', 'desirs-profonds', 'retrouver et honorer ses vrais désirs', 'Identité & Mission', false, true, false),
  ('Deuil', 'deuil', 'traverser la perte et faire le deuil d''un proche ou d''une situation', 'Vie & Expériences', true, true, false),
  ('Deuil périnatal & infertilité', 'deuil-perinatal-infertilite', 'le deuil de l''enfant attendu, perdu ou impossible', 'Vie & Expériences', false, true, false),
  ('Dharma', 'dharma', 'chemin de vie, mission karmique, raison d''incarnation', 'Spiritualité & Énergie', false, true, false),
  ('Disqualification de soi', 'disqualification-de-soi', 'se minimiser, se dénigrer — origines et guérison', 'Émotions & Psychologie', false, true, false),
  ('Dissociation', 'dissociation', 'se déconnecter de soi comme mécanisme de survie', 'Émotions & Psychologie', false, true, false),
  ('Divorce & séparation', 'divorce-separation', 'traverser, comprendre et se reconstruire', 'Vie & Expériences', false, true, false),
  ('Douleur chronique', 'douleur-chronique', 'le lien entre corps, émotions et mémoire physique', 'Corps & Somatique', false, true, false),
  ('Drama triangle', 'drama-triangle', 'triangle de Karpman — victime, sauveur, persécuteur', 'Relations & Liens', false, true, false),
  ('EFT (Tapping)', 'eft-tapping', 'Emotional Freedom Technique — libérer les émotions par les méridiens', 'Soins & Thérapies', false, true, false),
  ('EMDR', 'emdr', 'thérapie par les mouvements oculaires pour traiter les traumatismes', 'Soins & Thérapies', false, true, false),
  ('Ego', 'ego', 'comprendre l''ego, le dépasser sans le nier', 'Spiritualité & Énergie', false, true, false),
  ('Émotions', 'emotions', 'intelligence émotionnelle, identifier et traverser ses émotions', 'Émotions & Psychologie', false, true, false),
  ('Empathie', 'empathie', 'développer l''empathie et se protéger de l''empathie toxique', 'Relations & Liens', false, true, false),
  ('Empowerment', 'empowerment', 'reprendre son pouvoir personnel', 'Développement Personnel', false, true, false),
  ('Énergie vitale', 'energie-vitale', 'prana, chi, ki — comprendre et nourrir sa force de vie', 'Spiritualité & Énergie', false, true, false),
  ('Enfant intérieur', 'enfant-interieur', 'se reconnecter et guérir l''enfant blessé en soi', 'Blessures & Traumatismes', false, true, false),
  ('Ennéagramme', 'enneagramme', 'les 9 types de personnalité et leurs dynamiques profondes', 'Pratiques & Outils', false, true, false),
  ('Épigénétique', 'epigenetique', 'comment les traumatismes se transmettent d''une génération à l''autre', 'Corps & Somatique', false, true, false),
  ('Équilibre vie professionnelle / personnelle', 'equilibre-vie-professionnelle-personnelle', 'trouver son propre équilibre durable', 'Vie & Expériences', false, true, false),
  ('Estime de soi', 'estime-de-soi', 'construire une estime solide et indépendante du regard des autres', 'Développement Personnel', false, true, false),
  ('État de flow', 'etat-de-flow', 'entrer dans la zone — performance, créativité, présence totale', 'Développement Personnel', false, true, false),
  ('Éveil spirituel', 'eveil-spirituel', 'traverser les étapes d''un éveil — comprendre et intégrer', 'Spiritualité & Énergie', false, true, false),
  ('Famille toxique', 'famille-toxique', 'dynamiques dysfonctionnelles, bouc émissaire, enfant parentifié', 'Relations & Liens', false, true, false),
  ('Fascias & mémoire corporelle', 'fascias-memoire-corporelle', 'comment le corps stocke les émotions dans les tissus', 'Corps & Somatique', false, true, false),
  ('Fatigue émotionnelle', 'fatigue-emotionnelle', 'adrénaline chronique, épuisement nerveux et reconstruction', 'Émotions & Psychologie', false, true, false),
  ('Féminin sacré', 'feminin-sacre', 'retrouver, honorer et incarner le féminin profond', 'Spiritualité & Énergie', false, true, false),
  ('Fidélité à soi-même', 'fidelite-a-soi-meme', 'ne plus trahir ses propres valeurs pour plaire', 'Identité & Mission', false, true, false),
  ('Filiation', 'filiation', 'le lien aux parents et aux ancêtres — honorer sans porter', 'Relations & Liens', false, true, false),
  ('Fleurs de Bach', 'fleurs-de-bach', '38 élixirs floraux pour équilibrer les états émotionnels', 'Soins & Thérapies', false, true, false),
  ('Frontières & limites', 'frontieres-limites', 'poser des limites saines sans culpabilité', 'Développement Personnel', false, true, false),
  ('Frustration', 'frustration', 'comprendre la frustration comme signal de besoins non comblés', 'Émotions & Psychologie', false, true, false),
  ('Gaslighting', 'gaslighting', 'manipulation par la distorsion de la réalité — identifier et sortir', 'Relations & Liens', false, true, false),
  ('Générosité excessive', 'generosite-excessive', 'donner sans se vider — trouver l''équilibre du don', 'Développement Personnel', false, true, false),
  ('Géobiologie', 'geobiologie', 'l''influence de l''espace et des lieux sur l''énergie', 'Spiritualité & Énergie', false, true, false),
  ('Gratitude', 'gratitude', 'la pratique de la gratitude comme outil de transformation', 'Pratiques & Outils', false, true, false),
  ('Guérison', 'guerison', 'le processus global de guérison — étapes, spirales, rechutes', 'Développement Personnel', false, true, false),
  ('Honte', 'honte', 'comprendre et libérer la honte toxique', 'Émotions & Psychologie', false, true, false),
  ('Human Design', 'human-design', 'découvrir son type, son autorité et sa stratégie de vie', 'Pratiques & Outils', false, true, false),
  ('Hypervigilance', 'hypervigilance', 'toujours en alerte — reconnaître et déposer la vigilance excessive', 'Émotions & Psychologie', false, true, false),
  ('Hypersensibilité', 'hypersensibilite', 'être HSP — force, défis et épanouissement des âmes sensibles', 'Identité & Mission', false, true, false),
  ('Hypnose thérapeutique', 'hypnose-therapeutique', 'travail sur l''inconscient par l''hypnose et la transe', 'Soins & Thérapies', false, true, false),
  ('Identité', 'identite', 'construire et affirmer une identité solide et authentique', 'Identité & Mission', false, true, false),
  ('Identité de genre & sexualité', 'identite-de-genre-sexualite', 'explorer, comprendre et accepter sa nature profonde', 'Identité & Mission', false, true, false),
  ('Illusions', 'illusions', 'déconstruire les illusions sur l''amour, la vie, et soi-même', 'Développement Personnel', false, true, false),
  ('Incarnation', 'incarnation', 'être pleinement dans son corps, présent à sa vie', 'Corps & Somatique', false, true, false),
  ('Inconscient', 'inconscient', 'explorer les mécanismes inconscients qui pilotent notre vie', 'Émotions & Psychologie', false, true, false),
  ('Injustice', 'injustice', 'blessure d''injustice — la colère du juste et la guérison', 'Blessures & Traumatismes', false, true, false),
  ('Intuition', 'intuition', 'se reconnecter à son intuition', 'Développement Personnel', true, true, false),
  ('Isolement social', 'isolement-social', 'solitude subie, retrait du monde et reconnexion', 'Vie & Expériences', false, true, false),
  ('Jalousie & envie', 'jalousie-envie', 'comprendre la jalousie comme signal d''un besoin', 'Émotions & Psychologie', false, true, false),
  ('Joie profonde', 'joie-profonde', 'cultiver une joie qui ne dépend pas des conditions extérieures', 'Développement Personnel', false, true, false),
  ('Journal thérapeutique', 'journal-therapeutique', 'journaling comme pratique de connexion à soi', 'Pratiques & Outils', false, true, false),
  ('Jugement & regard des autres', 'jugement-regard-des-autres', 'se libérer du regard, de l''opinion, de la peur du rejet', 'Émotions & Psychologie', false, true, false),
  ('Jung & l''inconscient collectif', 'jung-linconscient-collectif', 'archétypes, ombre, synchronicités — l''héritage jungien', 'Pratiques & Outils', false, true, false),
  ('Karma', 'karma', 'lois karmiques, schémas répétitifs entre vies et libération', 'Spiritualité & Énergie', false, true, false),
  ('Kundalini', 'kundalini', 'énergie serpentine — éveil, montée et intégration', 'Spiritualité & Énergie', false, true, false),
  ('Lâcher-prise', 'lacher-prise', 'l''art de libérer ce qu''on ne peut pas contrôler', 'Développement Personnel', false, true, false),
  ('Leadership personnel', 'leadership-personnel', 'devenir le leader de sa propre vie', 'Identité & Mission', false, true, false),
  ('Liberté intérieure', 'liberte-interieure', 'construire une liberté qui vient de l''intérieur', 'Développement Personnel', false, true, false),
  ('Loi de l''attraction', 'loi-de-lattraction', 'vibration, manifestation et co-création avec l''univers', 'Spiritualité & Énergie', false, true, false),
  ('Loyautés invisibles', 'loyautes-invisibles', 'les loyautés familiales inconscientes qui nous retiennent', 'Blessures & Traumatismes', false, true, false),
  ('Lucidité onirique', 'lucidite-onirique', 'rêves lucides — explorer et transformer depuis le rêve', 'Pratiques & Outils', false, true, false),
  ('Masculin sacré', 'masculin-sacre', 'retrouver, équilibrer et incarner le masculin profond', 'Spiritualité & Énergie', false, true, false),
  ('Maternité & identité maternelle', 'maternite-identite-maternelle', 'devenir mère, perdre et retrouver soi dans la maternité', 'Vie & Expériences', false, true, false),
  ('Manipulation', 'manipulation', 'reconnaître les patterns manipulatoires et s''en protéger', 'Relations & Liens', false, true, false),
  ('Mécanismes de défense', 'mecanismes-de-defense', 'les protections inconscientes du psychisme', 'Émotions & Psychologie', false, true, false),
  ('Médecine ayurvédique', 'medecine-ayurvedique', 'connaissance de soi par les doshas et l''harmonie naturelle', 'Soins & Thérapies', false, true, false),
  ('Médecine traditionnelle chinoise', 'medecine-traditionnelle-chinoise', 'MTC — méridiens, énergie, organes et émotions', 'Soins & Thérapies', false, true, false),
  ('Méditation', 'meditation', 'pratique, bienfaits, et différentes formes de méditation', 'Pratiques & Outils', false, true, false),
  ('Médiumnité & perception extrasensorielle', 'mediumnite-perception-extrasensorielle', 'percevoir au-delà du visible', 'Spiritualité & Énergie', false, true, false),
  ('Mémoire cellulaire', 'memoire-cellulaire', 'les émotions stockées dans les cellules du corps', 'Corps & Somatique', false, true, false),
  ('Mémoire traumatique', 'memoire-traumatique', 'comment le trauma s''inscrit dans le corps et le cerveau', 'Blessures & Traumatismes', false, true, false),
  ('Méridiens énergétiques', 'meridiens-energetiques', 'les canaux d''énergie du corps et leur influence émotionnelle', 'Spiritualité & Énergie', false, true, false),
  ('Mission de vie', 'mission-de-vie', 'trouver sa mission et donner du sens', 'Identité & Mission', true, true, false),
  ('Mort & finitude', 'mort-finitude', 'apprivoiser la mort, réfléchir à la finitude pour mieux vivre', 'Vie & Expériences', false, true, false),
  ('Mouvement thérapeutique', 'mouvement-therapeutique', 'se guérir et se libérer par le mouvement du corps', 'Corps & Somatique', false, true, false),
  ('Narcissisme', 'narcissisme', 'le pervers narcissique — reconnaître, quitter et se reconstruire', 'Relations & Liens', false, true, false),
  ('Neurosciences émotionnelles', 'neurosciences-emotionnelles', 'comment le cerveau traite les émotions et construit nos réactions', 'Émotions & Psychologie', false, true, false),
  ('Neuroplasticité', 'neuroplasticite', 'la capacité du cerveau à se transformer et se recâbler', 'Corps & Somatique', false, true, false),
  ('Numérologie', 'numerologie', 'les vibrations des nombres comme clés de connaissance de soi', 'Pratiques & Outils', false, true, false),
  ('Régulation du système nerveux', 'regulation-du-systeme-nerveux', 'comprendre le SNA, sortir du mode survie', 'Corps & Somatique', false, true, false),
  ('Ombre (Shadow Work)', 'ombre-shadow-work', 'explorer et intégrer les parts rejetées de soi — héritage de Jung', 'Développement Personnel', false, true, false),
  ('Oracle & Tarot', 'oracle-tarot', 'outils de guidance intuitive et de connaissance de soi', 'Pratiques & Outils', false, true, false),
  ('Orgasme & sexualité sacrée', 'orgasme-sexualite-sacree', 'tantra, plaisir conscient, énergie sexuelle comme force créatrice', 'Corps & Somatique', false, true, false),
  ('Paix intérieure', 'paix-interieure', 'construire une paix qui résiste à la tempête', 'Développement Personnel', false, true, false),
  ('Pardon', 'pardon', 'apprendre à pardonner ou à avancer sans pardon', 'Développement Personnel', true, true, false),
  ('Parentalité consciente', 'parentalite-consciente', 'élever ses enfants en prenant soin de ses propres blessures', 'Relations & Liens', false, true, false),
  ('Passage à l''acte', 'passage-a-lacte', 'quitter la pensée pour entrer dans l''action', 'Développement Personnel', false, true, false),
  ('Perfectionnisme', 'perfectionnisme', 'comprendre le perfectionnisme et s''en libérer', 'Émotions & Psychologie', false, true, false),
  ('Peur', 'peur', 'comprendre, traverser et transformer toutes les formes de peur', 'Émotions & Psychologie', false, true, false),
  ('PNL (Programmation Neuro-Linguistique)', 'pnl-programmation-neuro-linguistique', 'reprogrammer ses réponses automatiques', 'Soins & Thérapies', false, true, false),
  ('Pleine conscience (Mindfulness)', 'pleine-conscience-mindfulness', 'vivre dans l''instant présent', 'Pratiques & Outils', false, true, false),
  ('Polarités (Yin / Yang)', 'polarites-yin-yang', 'équilibrer les forces opposées en soi', 'Spiritualité & Énergie', false, true, false),
  ('Procrastination', 'procrastination', 'comprendre ses racines profondes et s''en libérer', 'Émotions & Psychologie', false, true, false),
  ('Projection psychologique', 'projection-psychologique', 'reconnaître ce qu''on projette sur les autres', 'Émotions & Psychologie', false, true, false),
  ('Protection énergétique', 'protection-energetique', 'se protéger des énergies extérieures envahissantes', 'Spiritualité & Énergie', false, true, false),
  ('Psychogénéalogie', 'psychogenealogie', 'libérer les schémas répétitifs transmis par la famille', 'Soins & Thérapies', false, true, false),
  ('Psychosomatique', 'psychosomatique', 'quand le corps exprime ce que l''âme tait', 'Corps & Somatique', false, true, false),
  ('PTSD / C-PTSD', 'ptsd-c-ptsd', 'trouble de stress post-traumatique simple et complexe', 'Blessures & Traumatismes', false, true, false),
  ('Qi Gong & Tai Chi', 'qi-gong-tai-chi', 'énergie et mouvement pour harmoniser corps et esprit', 'Pratiques & Outils', false, true, false),
  ('Résilience', 'resilience', 'développer une force intérieure durable', 'Développement Personnel', true, true, false),
  ('Relation à l''argent', 'relation-a-largent', 'les croyances et blessures autour de l''abondance et de la valeur', 'Vie & Expériences', false, true, false),
  ('Relation au corps', 'relation-au-corps', 'réconciliation avec son corps, son image et son espace', 'Corps & Somatique', false, true, false),
  ('Relation au temps', 'relation-au-temps', 'rapport au passé, au futur et à l''instant présent', 'Vie & Expériences', false, true, false),
  ('Relation au travail', 'relation-au-travail', 'sens, identité professionnelle, épuisement et vocation', 'Vie & Expériences', false, true, false),
  ('Relations toxiques', 'relations-toxiques', 'les reconnaître et s''en libérer', 'Relations & Liens', true, true, false),
  ('Reiki', 'reiki', 'transmission d''énergie vitale par les mains', 'Soins & Thérapies', false, true, false),
  ('Respiration', 'respiration', 'techniques de respiration pour réguler, libérer et transformer', 'Pratiques & Outils', false, true, false),
  ('Rêves', 'reves', 'interpréter les rêves comme messages de l''inconscient', 'Spiritualité & Énergie', false, true, false),
  ('Rituels de soin', 'rituels-de-soin', 'créer des rituels personnels de reconnexion et de guérison', 'Pratiques & Outils', false, true, false),
  ('Santé mentale', 'sante-mentale', 'prendre soin de son équilibre émotionnel', 'Émotions & Psychologie', true, true, false),
  ('Schémas répétitifs', 'schemas-repetitifs', 'comprendre et défaire les patterns qui se rejouent sans cesse', 'Émotions & Psychologie', false, true, false),
  ('Sécurité émotionnelle', 'securite-emotionnelle', 'construire une sécurité intérieure stable', 'Développement Personnel', false, true, false),
  ('Self-care', 'self-care', 'prendre soin de soi sans culpabilité', 'Pratiques & Outils', false, true, false),
  ('Sensibilité & hypersensibilité', 'sensibilite-hypersensibilite', 'vivre et s''épanouir en tant que personne très sensible', 'Identité & Mission', false, true, false),
  ('Sexualité', 'sexualite', 'libérer, comprendre et honorer sa sexualité', 'Corps & Somatique', false, true, false),
  ('Shadow Work', 'shadow-work', 'le travail de l''ombre — intégrer ce qu''on rejette en soi', 'Développement Personnel', false, true, false),
  ('Solitude', 'solitude', 'apprivoiser la solitude comme espace de croissance', 'Vie & Expériences', false, true, false),
  ('Somatique', 'somatique', 'travail corporel pour libérer les tensions émotionnelles', 'Corps & Somatique', false, true, false),
  ('Son & vibrations', 'son-vibrations', 'sound healing, bols tibétains, mantras, guérison par le son', 'Soins & Thérapies', false, true, false),
  ('Spiritualité', 'spiritualite', 'développer une pratique spirituelle et pleine conscience', 'Spiritualité & Énergie', true, true, false),
  ('Stress', 'stress', 'apprendre à réguler le stress quotidien', 'Émotions & Psychologie', true, true, false),
  ('Subconscient', 'subconscient', 'explorer les profondeurs qui pilotent nos choix', 'Émotions & Psychologie', false, true, false),
  ('Synchronicités', 'synchronicites', 'reconnaître les coïncidences significatives comme guidances', 'Spiritualité & Énergie', false, true, false),
  ('Syndromes (enfant parentifié, bouc émissaire…)', 'syndromes-enfant-parentifie-bouc-emissaire', 'les rôles familiaux et leurs effets durables', 'Blessures & Traumatismes', false, true, false),
  ('Tantra', 'tantra', 'énergie, éveil et sexualité sacrée', 'Spiritualité & Énergie', false, true, false),
  ('Trahison', 'trahison', 'guérir d''une trahison — confiance brisée et reconstruction', 'Blessures & Traumatismes', false, true, false),
  ('Trans-générationnel', 'trans-generationnel', 'héritage familial, répétitions entre générations et libération', 'Blessures & Traumatismes', false, true, false),
  ('Traumatisme', 'traumatisme', 'guérir les blessures d''enfance : violence, abus, négligence', 'Blessures & Traumatismes', true, true, false),
  ('Triggers émotionnels', 'triggers-emotionnels', 'identifier ses déclencheurs et reprendre le contrôle', 'Émotions & Psychologie', false, true, false),
  ('TRE (Tension Release Exercises)', 'tre-tension-release-exercises', 'libérer le stress et le trauma stockés par le tremblement corporel', 'Soins & Thérapies', false, true, false),
  ('Unité & connexion universelle', 'unite-connexion-universelle', 'le sentiment d''appartenir à un tout plus grand', 'Spiritualité & Énergie', false, true, false),
  ('Urgence chronique', 'urgence-chronique', 'désactiver le mode survie permanent', 'Émotions & Psychologie', false, true, false),
  ('Valeurs', 'valeurs', 'identifier et vivre en accord avec ses valeurs profondes', 'Identité & Mission', false, true, false),
  ('Vide existentiel', 'vide-existentiel', 'le sentiment de vide — comprendre et traverser', 'Émotions & Psychologie', false, true, false),
  ('Vie intérieure', 'vie-interieure', 'développer une vie intérieure riche', 'Spiritualité & Énergie', false, true, false),
  ('Violence physique', 'violence-physique', 'se libérer des violences physiques subies', 'Blessures & Traumatismes', true, true, false),
  ('Violence verbale & psychologique', 'violence-verbale-psychologique', 'reconnaître et guérir des violences psychologiques', 'Blessures & Traumatismes', true, true, false),
  ('Vibrations & fréquences', 'vibrations-frequences', 'la science vibratoire — son, eau, pensées et matière (exp. du riz)', 'Spiritualité & Énergie', false, true, false),
  ('Visualisation créatrice', 'visualisation-creatrice', 'techniques de visualisation pour manifester et guérir', 'Pratiques & Outils', false, true, false),
  ('Vulnérabilité', 'vulnerabilite', 'la force paradoxale de la vulnérabilité — Brené Brown et au-delà', 'Développement Personnel', false, true, false),
  ('Yoga', 'yoga', 'yoga comme outil de transformation, de présence et de guérison', 'Pratiques & Outils', false, true, false),
  ('Zones d''ombre culturelles', 'zones-dombre-culturelles', 'les tabous collectifs qui conditionnent en silence', 'Vie & Expériences', false, true, false)
ON CONFLICT (slug) DO UPDATE SET
  subtitle = COALESCE(EXCLUDED.subtitle, douleurs.subtitle),
  category = COALESCE(EXCLUDED.category, douleurs.category),
  is_original = COALESCE(EXCLUDED.is_original, douleurs.is_original);
